# Generated by Django 5.1.3 on 2024-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=50)),
                ('asset', models.CharField(max_length=100)),
                ('asset_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('resolution_time_stamp', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('duration_seconds', models.FloatField()),
                ('device_id', models.IntegerField()),
                ('asset_id', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('fault_type', models.CharField(max_length=50)),
            ],
        ),
    ]
