# Generated by Django 5.1.3 on 2024-11-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='device_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='time_stamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
